fix: do not exit on Geoclue failure and add a second path to the agent
pop-os/cosmic-settings-daemon pull request #51
Opened 2024-09-07 06:29 UTC by lazytanuki

Hi !

This fixes #45, which was caused by a difference in paths to the Geoclue agent on some other distros. I also made it so the failure to launch Geoclue doesn't terminate the settings daemon.

Thanks !

2024-09-07 22:44 UTC, fulalas commented
Thanks for taking a look at this!

I have a question: what are the consequences of not having Geoclue agent available for `cosmic-settings-daemon`?

2024-09-08 12:55 UTC, lazytanuki commented
I am not sure, I didn't see anything from what I've tested without the agent, but I think it is better than having the desktop up and running without the settings daemon, which led to quite messy situations ^^

2024-09-08 20:33 UTC, Drakulix requested changes
Thanks! While the change to not exit the daemon, if geoclue is missing is certainly correct and very welcome, we shouldn't start listing even more paths.

Instead the path should be configurable at build time, so different distributions can insert the right thing here.

Inspiration for that can e.g. be taken from cosmic-session, which allows the path to xdg-desktop-portal-cosmic to be overridden at build time: https://github.com/pop-os/cosmic-session/blob/master/Justfile#L12

2024-09-08 21:12 UTC, lazytanuki commented
Makes more sense indeed. The `GEOCLUE_AGENT` build env var is already used here, so I guess there's no need for a `justfile` yet?

2024-09-08 23:46 UTC, wash2 commented
> Makes more sense indeed. The `GEOCLUE_AGENT` build env var is already used here, so I guess there's no need for a `justfile` yet?

It is actually already included in the makefile, so yeah. No changes should be necessary for that.

2024-09-08 23:46 UTC, wash2 approved these changes

2024-09-08 23:50 UTC, merged